// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SpJsonTest.Models
{
    [Table("student")]
    public partial class Student
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("fname")]
        [StringLength(50)]
        public string Fname { get; set; }
        [Column("lname")]
        [StringLength(50)]
        public string Lname { get; set; }
        [Column("mobile")]
        [StringLength(15)]
        public string Mobile { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("city")]
        [StringLength(100)]
        public string City { get; set; }
    }
}